### ISSUE TITLE
Where is `manage.py`? Please submit all issues on this tab. Check your Pull Requests!

### ISSUE THREAD

**Issue by JChrisWolfe** [susantoj/Cablesizer#3]
Saw your link from [Upwork](https://www.upwork.com/job/need-quick-help-setting-old-django-project-run_~0110d1ded70a1fd3c9/). Is this Django version 0.x or 1.x to your knowledge?

Don't need $$$ (People would charge way more) just a reference saying I've helped you if successful, assuming if the issues still exist. Show that I've contributed on this GitHub. Same idea with other GitHub users.

This GitHub you can submit issues, add necessary labels, and take advantage of the open source movement even if you must change the `SECRET_KEY` later and change other settings if needed like who is superuser later on!

Also check your [Pull Requests](https://github.com/susantoj/Cablesizer/pulls). [AlexKorob](https://github.com/AlexKorob) did what you've requested.

And Check your [Closed Pull Requests](https://github.com/susantoj/Cablesizer/pulls?q=is%3Apr+is%3Aclosed).

Any questions? Please let us know (including other GitHub users).

**Comment by susantoj** [comment]
Hi Chris, thanks for your message - that Upwork request was not actually mine!

**Comment by JChrisWolfe** [comment]
Interesting! Someone trying to setup other's work as their own and willing
to spend some cash to do it.

I kinda want to know who is doing that but I've got other priorities. Have
a good night from Eastern Standard Time Zone and Best Regards.
